-- "unknown" VARCHAR lengths standardised to 50 for easy consistency.
-- Lifan: keeping 50, its not mentioned in brief.

-- Lifan: I've made some foreign keys DEFERRABLE INITIALLY IMMEDIATE and added some checkers.
CREATE TABLE CATEGORY (
	CATEGORY_TYPE VARCHAR(50) PRIMARY KEY,
	MAX_TIER INTEGER NOT NULL CHECK (MAX_TIER >= 1)
);


CREATE TABLE YARD (
	CODE VARCHAR(50) PRIMARY KEY,
	CATEGORY_TYPE VARCHAR(50) NOT NULL
		REFERENCES CATEGORY (CATEGORY_TYPE)
		DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE POSITION(
	BAY INTEGER CHECK (BAY >= 0),
	ROW INTEGER CHECK (ROW >= 0),
	TIER INTEGER CHECK (TIER >= 1),
	
	CODE VARCHAR(50) REFERENCES YARD (CODE)
		DEFERRABLE INITIALLY IMMEDIATE, 
	-- doesn't need to specify NOT NULL, since it's part of pkey i think
	PRIMARY KEY (BAY, ROW, TIER, CODE)
);

CREATE TABLE COUNTRY (
	NAME VARCHAR(100) PRIMARY KEY, -- longest name is 54
	CONTINENT VARCHAR(15) NOT NULL -- longest is 12
);

CREATE TABLE CITY (
	NAME VARCHAR(200), -- bangkok's city name is 164
	COUNTRY_NAME VARCHAR(60) REFERENCES COUNTRY (NAME)
		DEFERRABLE INITIALLY IMMEDIATE,
	PRIMARY KEY (NAME, COUNTRY_NAME)
);

CREATE TABLE COMPANY (
	COMPANY_CODE VARCHAR(50) PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	
	ADDRESS VARCHAR(50) NOT NULL, -- should we regex?  Lifan: nah, brief didnt mention a format for address
	POSTAL_CODE VARCHAR(50) NOT NULL, -- some countries have alphanumeric postal codes
	CITY_NAME VARCHAR(200) NOT NULL,
	COUNTRY_NAME VARCHAR(60) NOT NULL,
	FOREIGN KEY (CITY_NAME, COUNTRY_NAME) 
		REFERENCES CITY (NAME, COUNTRY_NAME)
		DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE CONTAINER (
	ISO_6346 VARCHAR(15) PRIMARY KEY, -- iso is 11 char
	CONTENT VARCHAR(50) NOT NULL,
	COMPANY_CODE VARCHAR(50) NOT NULL
		REFERENCES COMPANY (COMPANY_CODE)
		DEFERRABLE INITIALLY IMMEDIATE,
	--Lifan: check it matches
	CONSTRAINT CONTAINER_OWNER_PREFIX
		CHECK (SUBSTRING(ISO_6346 FROM 1 FOR 3) = COMPANY_CODE)
);

CREATE TABLE STORED_AT (
	ISO_6346 VARCHAR(15) REFERENCES CONTAINER (ISO_6346),
	BAY INTEGER NOT NULL,
	ROW INTEGER NOT NULL,
	TIER INTEGER NOT NULL,
	CODE VARCHAR(50) NOT NULL,
	FOREIGN KEY (BAY, ROW, TIER, CODE) 
			REFERENCES POSITION (BAY, ROW, TIER, CODE)
			DEFERRABLE INITIALLY IMMEDIATE,
	
	PRIMARY KEY (ISO_6346),
	UNIQUE (BAY, ROW, TIER, CODE)
);

CREATE TABLE BERTH (
	LONGITUDE NUMERIC(9, 6),
	LATITUDE NUMERIC(8, 6),
	-- Lifan: is code VARCHAR better? saw B1 and B2
	CODE VARCHAR(50) PRIMARY KEY,
	CONSTRAINT BERTH_POSITION UNIQUE (LONGITUDE, LATITUDE)
);

CREATE TABLE SHIP (
	MMSI VARCHAR(9) PRIMARY KEY,
	IMO_NUMBER VARCHAR(10) UNIQUE NOT NULL,
	CALL_SIGN VARCHAR(20) UNIQUE NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	WIDTH DECIMAL(8, 2) NOT NULL CHECK (WIDTH > 0),
	LENGTH DECIMAL(8, 2) NOT NULL CHECK (LENGTH > 0),

	-- Lifan: dock relationship 
	BERTH_CODE VARCHAR(50) NOT NULL UNIQUE,
	FOREIGN KEY (BERTH_CODE) REFERENCES BERTH (CODE)
		DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE LOADED_ON (
	MMSI VARCHAR(9) REFERENCES SHIP (MMSI),
	ISO_6346 VARCHAR(15) REFERENCES CONTAINER (ISO_6346),
	PRIMARY KEY (ISO_6346)
)



--Lifan: TOADD: Every CONTAINER must appear in exactly one of STORED_AT or LOADED_ON.  
-- POSITION.TIER must not exceed the MAX_TIER of yard. 
-- A container above tier 1 must ahve an oocupied position immediately below it in the same yard, bay and row.
