-- "unknown" VARCHAR lengths standardised to 50 for easy consistency.
CREATE TABLE CATEGORY (
	CATEGORY_TYPE VARCHAR(50) PRIMARY KEY,
	MAX_TIER INTEGER NOT NULL
);

-- should code be int or varchar?
CREATE TABLE YARD (
	CODE VARCHAR(50) PRIMARY KEY,
	CATEGORY_TYPE VARCHAR(50) REFERENCES CATEGORY (CATEGORY_TYPE) NOT NULL
);

CREATE TABLE POSITION(
	BAY INTEGER,
	ROW INTEGER,
	TIER INTEGER,
	CODE VARCHAR(50) REFERENCES YARD (CODE), -- doesn't need to specify NOT NULL, since it's part of pkey i think
	PRIMARY KEY (BAY, ROW, TIER, CODE)
);

CREATE TABLE COUNTRY (
	NAME VARCHAR(100) PRIMARY KEY, -- longest name is 54
	CONTINENT VARCHAR(15) NOT NULL -- longest is 12
);

CREATE TABLE CITY (
	NAME VARCHAR(200), -- bangkok's city name is 164
	COUNTRY_NAME VARCHAR(60) REFERENCES COUNTRY (NAME),
	PRIMARY KEY (NAME, COUNTRY_NAME)
);

CREATE TABLE COMPANY (
	COMPANY_CODE VARCHAR(50) PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	ADDRESS VARCHAR(50) NOT NULL, -- should we regex?
	POSTAL_CODE VARCHAR(50) NOT NULL, -- some countries have alphanumeric postal codes
	CITY_NAME VARCHAR(200) NOT NULL,
	COUNTRY_NAME VARCHAR(60) NOT NULL,
	FOREIGN KEY (CITY_NAME, COUNTRY_NAME) REFERENCES CITY (NAME, COUNTRY_NAME)
);

CREATE TABLE CONTAINER (
	ISO_6346 VARCHAR(15) PRIMARY KEY, -- iso is 11 char
	CONTENT VARCHAR(50) NOT NULL,
	COMPANY_CODE VARCHAR(50) REFERENCES COMPANY (COMPANY_CODE) NOT NULL
);

CREATE TABLE STORED_AT (
	ISO_6346 VARCHAR(15) REFERENCES CONTAINER (ISO_6346),
	BAY INTEGER,
	ROW INTEGER,
	TIER INTEGER,
	CODE VARCHAR(50),
	FOREIGN KEY (BAY, ROW, TIER, CODE) REFERENCES POSITION(BAY, ROW, TIER, CODE),
	PRIMARY KEY (ISO_6346, BAY, ROW, TIER, CODE)
);

CREATE TABLE BERTH (
	LONGITUDE NUMERIC(9, 6),
	LATITUDE NUMERIC(8, 6),
	CODE INTEGER PRIMARY KEY CHECK (CODE > 0), -- assume > 0
	CONSTRAINT BERTH_POSITION UNIQUE (LONGITUDE, LATITUDE)
);

CREATE TABLE SHIP (
	MMSI VARCHAR(9) PRIMARY KEY,
	IMO_NUMBER VARCHAR(10) UNIQUE NOT NULL,
	CALL_SIGN VARCHAR(20) UNIQUE NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	WIDTH DECIMAL(8, 2) NOT NULL CHECK (WIDTH > 0),
	LENGTH DECIMAL(8, 2) NOT NULL CHECK (LENGTH > 0)
);

CREATE TABLE LOADED_ON (
	MMSI VARCHAR(9) REFERENCES SHIP (MMSI),
	ISO_6346 VARCHAR(15) REFERENCES CONTAINER (ISO_6346),
	PRIMARY KEY (MMSI, ISO_6346)
)